### ISSUE TITLE
Better naming for the models 

### ISSUE THREAD

**Issue by Shoray2002** [iiitl/molars#1]
The .obj models in the /models are all named wrong.
Things to be done:
- [x]  Change filenames to acceptable names and also update the file-name array in index.html
- [x]  Rename variable names throughout the project to reflect those name changes

**Modular Issue - Individual tasks can be done seperately**

**Comment by schrodingerr** [comment]
Hello @Shoray2002 , just wanted to know what should i name those .obj files any specific criteria?

**Comment by Shoray2002** [comment]
Hi, there is no specific scheme for naming
but the names should be concise and describe the model type fairly 
like front_incisor or something. you can also go the numbering route

**Comment by KanishkDadhich** [comment]
Hello @Shoray2002 . I would like to work on this 1st issue of changing the models name in the /models folder.
I'm curious, if can I follow the numbering route (ex- model1,model2,model3), as you said above.
Thanks:)

**Comment by KanishkDadhich** [comment]
Also I can see that this website doesn't have a favicon. It would look quite captivating if this had one. Hence, I would like to work on this issue as well.
Thanks:)

**Comment by Shoray2002** [comment]
> Also I can see that this website doesn't have a favicon. It would look quite captivating if this had one. Hence, I would like to work on this issue as well.
> Thanks:)
> 
> 

Make a separate issue for that and I will assign it to you

**Comment by Shoray2002** [comment]
> Hello @Shoray2002 . I would like to work on this 1st issue of changing the models name in the /models folder.
> I'm curious, if can I follow the numbering route (ex- model1,model2,model3), as you said above.
> Thanks:)

Take on issues one at a time
Letme know which one you assigned to you first?

**Comment by axshatj** [comment]
hey @Shoray2002 , i made a PR for task 1 of this issue can you verify it.

**Comment by KanishkDadhich** [comment]
Hey @Shoray2002 I've made a separate issue related to the favicon. Please assign this to me.
Thanks:)

**Comment by Shoray2002** [comment]
updated name of tooth models #9
